name: Build & Test 🧪

on:
  push:
    branches:
      - master
      - dev

jobs:
  BuildAndTestApplication:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore moldme/moldme.csproj

      - name: Clean application
        run: dotnet clean moldme/moldme.csproj

      - name: Build application
        run: dotnet build moldme/moldme.csproj --configuration Debug # Use Debug for more detailed output during development

      - name: Test application
        run: dotnet test moldme/moldme.csproj --verbosity detailed # Increased verbosity for better logging


