name: Build & Test 🧪

on:
  push:
    branches:
      - master
      - dev
      - dev-*  # Captura branches que começam com 'dev-'
  pull_request:
    branches:
      - master
      - dev
      - dev-*  # Captura pull requests para essas branches

jobs:
  BuildAndTestApplication:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore moldme/moldme.csproj

      - name: Clean application
        run: dotnet clean moldme/moldme.csproj

      - name: Build application
        run: dotnet build moldme/moldme.csproj --configuration Debug

      - name: Test application
        run: dotnet test moldme/moldme.csproj --verbosity detailed


